package org.shahani.ddb.logic;

import java.sql.*;

import org.shahani.ddb.db.DatabaseConnection;

public class CarRegister {
	private String car_model ;
	private String car_brand ;
	private String car_category ;
	private String image ;
	

	public String execute(){
		Connection connection = DatabaseConnection.getConnection(); 
		try{
			String insertQuery = "INSERT INTO car(id,car_model,car_brand,car_category,image) VALUES(car_seq.nextval,?,?,?,?,)" ;
			String generatedColums[] = {"id"};
			
			PreparedStatement ps = connection.prepareStatement(insertQuery, generatedColums);
			ps.setString(1, getCar_model());
			ps.setString(2, getCar_brand());
			ps.setString(3, getCar_category());
			ps.setString(4, getImage());
			ps.executeQuery();
			
			ResultSet tablekeys = ps.getGeneratedKeys();
			tablekeys.next();
			int autoGeneratedId = tablekeys.getInt(1);
			
			System.out.println(autoGeneratedId);
			
			ps.close();
			connection.commit();
		}catch(SQLException e){
			e.printStackTrace();
			return "failure";
		}catch(Exception e){
			e.printStackTrace();
			return "failure";
		}
		return "success" ;
	}
	
	public String getCar_model() {
		return car_model;
	}
	public void setCar_model(String car_model) {
		this.car_model = car_model;
	}
	public String getCar_brand() {
		return car_brand;
	}
	public void setCar_brand(String car_brand) {
		this.car_brand = car_brand;
	}
	public String getCar_category() {
		return car_category;
	}
	public void setCar_category(String car_category) {
		this.car_category = car_category;
	}
	public String getImage() {
		return image;
	}
	public void setImage(String image) {
		this.image = image;
	}
	
}
