package org.shahani.ddb.logic;

import java.sql.*;

import org.shahani.ddb.db.DatabaseConnection;

public class DriverRegister {
	private String first_name;
	private String last_name;
	private String email;
	private String password;
	private String city;
	private int contact;
	private int location_id;
	private int car_id;
	private int document_id;
	
	public String execute(){
		Connection connection = DatabaseConnection.getConnection(); 
		try{
			String insertQuery = "INSERT INTO driver(id,first_name,last_name,email_id,password,city,location_id,contact_number,car_id,document_id) VALUES(driver_seq.nextval,?,?,?,?,?,?,?,?,?)" ;
			
			String generatedColums[] = {"id"};
			
			PreparedStatement ps = connection.prepareStatement(insertQuery, generatedColums);
			ps.setString(1, getFirst_name());
			ps.setString(2, getLast_name());
			ps.setString(3, getEmail());
			ps.setString(4, getPassword());
			ps.setString(5, getCity());
			ps.setInt(6, getLocation_id());
			ps.setInt(7, getContact());
			ps.setInt(8, getCar_id());
			ps.setInt(9, getDocument_id());
			ps.executeQuery();
			
			ResultSet tablekeys = ps.getGeneratedKeys();
			tablekeys.next();
			int autoGeneratedId = tablekeys.getInt(1);
			
			System.out.println(autoGeneratedId);
			
			ps.close();
			connection.commit();
		}catch(SQLException e){
			e.printStackTrace();
			return "failure";
		}catch(Exception e){
			e.printStackTrace();
			return "failure";
		}
		return "success" ;
	}
	
	
	public String getFirst_name() {
		return first_name;
	}
	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}
	public String getLast_name() {
		return last_name;
	}
	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public int getContact() {
		return contact;
	}
	public void setContact(int contact) {
		this.contact = contact;
	}
	public int getLocation_id() {
		return location_id;
	}
	public void setLocation_id(int location_id) {
		this.location_id = location_id;
	}
	public int getCar_id() {
		return car_id;
	}
	public void setCar_id(int car_id) {
		this.car_id = car_id;
	}
	public int getDocument_id() {
		return document_id;
	}
	public void setDocument_id(int document_id) {
		this.document_id = document_id;
	}
	
}
