package org.shahani.ddb.logic;

import java.sql.*;
import org.shahani.ddb.db.DatabaseConnection;

public class PersonRegister {
	private String first_name;
	private String last_name;
	private String email;
	private String password;
	private String city;
	private int wallet;
	private int location;

	public String execute(){
		Connection connection = DatabaseConnection.getConnection(); 
		try{
			String insertQuery = "INSERT INTO person(id,first_name,last_name,email_id,password,city,wallet_amount,location_id) VALUES(person_seq.nextval,?,?,?,?,?,?,?)" ;
			
			String generatedColums[] = {"id"};
			
			PreparedStatement ps = connection.prepareStatement(insertQuery, generatedColums);
			ps.setString(1, getFirst_name());
			ps.setString(2, getLast_name());
			ps.setString(3, getEmail());
			ps.setString(4, getPassword());
			ps.setString(5, getCity());
			ps.setInt(6, getWallet());
			ps.setInt(7, getLocation());
			ps.executeQuery();
			
			ResultSet tablekeys = ps.getGeneratedKeys();
			tablekeys.next();
			int autoGeneratedId = tablekeys.getInt(1);
			
			System.out.println(autoGeneratedId);
			
			ps.close();
			connection.commit();
		}catch(SQLException e){
			e.printStackTrace();
			return "failure";
		}catch(Exception e){
			e.printStackTrace();
			return "failure";
		}
		return "success" ;
	}
	
	public String getFirst_name() {
		return first_name;
	}
	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}
	public String getLast_name() {
		return last_name;
	}
	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	

	public int getWallet() {
		return wallet;
	}

	public void setWallet(int wallet) {
		this.wallet = wallet;
	}

	public int getLocation() {
		return location;
	}

	public void setLocation(int location) {
		this.location = location;
	}
}
